from sign_language_tools.pose.mediapipe.facemesh import (
    FACEMESH_LIPS,
    FACEMESH_LEFT_EYE,
    FACEMESH_RIGHT_EYE,
    FACEMESH_LEFT_IRIS,
    FACEMESH_RIGHT_IRIS,
    FACEMESH_LEFT_EYEBROW,
    FACEMESH_RIGHT_EYEBROW,
)


def _vertices_from_edges(edges):
    return tuple(sorted(set(sum(edges, ()))))


LIPS_VERTICES = _vertices_from_edges(FACEMESH_LIPS)

LEFT_EYE_VERTICES = _vertices_from_edges(FACEMESH_LEFT_EYE)
RIGHT_EYE_VERTICES = _vertices_from_edges(FACEMESH_RIGHT_EYE)

LEFT_IRIS_VERTICES = _vertices_from_edges(FACEMESH_LEFT_IRIS)
RIGHT_IRIS_VERTICES = _vertices_from_edges(FACEMESH_RIGHT_IRIS)

LEFT_EYEBROW_VERTICES = _vertices_from_edges(FACEMESH_LEFT_EYEBROW)
RIGHT_EYEBROW_VERTICES = _vertices_from_edges(FACEMESH_RIGHT_EYEBROW)

LEFT_FULL_EYE_VERTICES = LEFT_EYE_VERTICES + LEFT_IRIS_VERTICES + LEFT_EYEBROW_VERTICES
RIGHT_FULL_EYE_VERTICES = RIGHT_EYE_VERTICES + RIGHT_IRIS_VERTICES + RIGHT_EYEBROW_VERTICES
