site_name: Sign Language Tools

theme:
  name: "material"
  palette:
    primary: cyan

plugins:
  - mkdocstrings


nav:
  - Home: index.md
  - Visualization: visualization.md
  - Pose: pose.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
