site_name: Sign Language Tools

theme:
  name: "material"

plugins:
  - mkdocstrings:
        docstring_style: numpy


nav:
  - index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
