# pyproject.toml

[build-system]
requires        = ["setuptools>=70.2.0", "wheel"]
build-backend   = "setuptools.build_meta"

[project]
name = "sign-language-tools"
version = "1.0.0"
description = "Python library containing various tools for sign language processing"
readme = "README.md"
authors = [
    { name = "Pierre Poitier", email = "pierre.poitier@unamur.be" },
    { name = "Jérôme Fink", email = "jerome.fink@unamur.be" }
]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["sign language", "machine learning", "data augmentation", "visualization"]
dependencies = [
    "matplotlib",
    "mediapipe",
    "numpy",
    "opencv-python",
    "pandas",
    "plotly",
    "scipy",
    "scikit-learn",
    "torch",
    "tqdm",
    "vidgear",
]
requires-python = ">=3.10"

[project.optional-dependencies]
video-backends = [
    "av",
    "decord",
]
dev = [
    "black",
    "pip-tools",
    "pytest",
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
]

[project.urls]
Homepage = "https://github.com/ppoitier/sign-language-tools"

[project.scripts]
realpython = "sign_language_tools.__main__:main"